steps:
  # It's unclear why we need this, but bazel appears to need it sometimes.
  - name: 'l.gcr.io/google/debian9:latest'
    args: ['chmod', 'a+rx', '-R', '/workspace']

  # We have to build and load the builder image first, so it can be used in the next step.
  # Using "run" instead of "build" loads the built image into the daemon.
  - name: gcr.io/cloud-builders/bazel
    args: ['run', '--incompatible_disable_deprecated_attr_params=false', '--incompatible_string_join_requires_strings=false', '--incompatible_new_actions_api=false', '--incompatible_no_support_tools_in_action_inputs=false', '//debian/reproducible:debian${_VERSION_NUMBER}']
  
  # Give the image the right tag, and let CloudBuild push it.
  - name: gcr.io/cloud-builders/docker
    args: ['tag', 'bazel/debian/reproducible:debian${_VERSION_NUMBER}', '${_REPO}/debian${_VERSION_NUMBER}:${_TAG}']

images: ['${_REPO}/debian${_VERSION_NUMBER}:${_TAG}']
