workspace(name = "python")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# `sudo apt install libssl-dev`

_configure = "./configure --prefix=$(pwd)/qpx_out"

new_git_repository(
    name = "python3",
    remote = "./upstream",
    tag = PYTHON_VER,
    build_file_content = """
exports_files(["qpx_bin"])
filegroup(
    name = "files",
    srcs = glob(["qpx_out/**"], exclude = ["**/* *"]),
    visibility = ["//visibility:public"],
)
""",
    patch_cmds = [
        "mkdir $(pwd)/qpx_out",
        _configure,
        "make",
        "make install",
        "ln -s qpx_out/bin/python3 qpx_bin",
    ],
)

http_archive(
    name = "python2",
    build_file_content = """
exports_files(["qpx_bin"])
filegroup(
    name = "files",
    srcs = glob(["qpx_out/**"], exclude = ["**/* *"]),
    visibility = ["//visibility:public"],
)
""",
    patch_cmds = [
        "mkdir $(pwd)/qpx_out",
        _configure,
        "make",
        "make install",
        "ln -s qpx_out/bin/python qpx_bin",
    ],
    sha256 = "dfab5ec723c218082fe3d5d7ae17ecbdebffa9a1aea4d64aa3a2ecdd2e795864",
    strip_prefix = "Python-2.7.9",
    urls = ["https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tar.xz"],
)

http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.1.0/rules_python-0.1.0.tar.gz",
    sha256 = "b6d46438523a3ec0f3cead544190ee13223a52f6a6765a29eae7b7cc24cc83a0",
)

load("@rules_python//python:pip.bzl", "pip_install")


pip_install(
    #extra_pip_args = ["-v"],
    #pip_data_exclude = ["**/* */**"],

    #python_interpreter (path)
    #python_interpreter_target = "@python3//:qpx_bin",

    #quiet = False,

    requirements = "//:requirements.txt",
)

#register_toolchains("//:my_py_toolchain")
