package(default_visibility = ["//visibility:public"])

py_binary(
    name = "git",
    srcs = ["git.py"],
    srcs_version = "PY2AND3",
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_tools//third_party/py/gflags",
    ],
)
