ARG VERSION=master
FROM qbrn.reg/ubu-dev:std

ENV JULIA_PATH /usr/local/julia
ENV PATH $JULIA_PATH/bin:$PATH

ENV JULIA_VERSION ${VERSION}
ENV JULIA_GPG 3673DF529D9049477F76B37566E3C7DC03D6E495

# RUN set -eux; \
#	julia --version

# CMD ["julia"]
CMD ["bash"]


